#! /bin/bash
# postrm script

set -e


# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

if [ "$1" = "purge" ] || [ "$1" = "remove" ] ; then
        echo 'Removing rc scripts for PowerFolder-Server' 1>&2
        update-rc.d -f powerfolder-server remove 1>&2 || exit 1
fi

if [ "$1" = "purge" ] ; then
    if getent passwd powerfolder > /dev/null ; then
        echo 'Removing system-user for PowerFolder-Server' 1>&2
        deluser --quiet --remove-home powerfolder || exit 1
    fi
fi

exit 0
